#!/usr/bin/env bash
set -Eeuo pipefail

main() {
  repository="$1"
  currentVersion="${2//v}"

  remoteVersion=$(curl --silent --show-error --fail "https://api.github.com/repos/$repository/releases/latest" | jq -r .tag_name)
  parsedRemoteVersion="${remoteVersion//v}"

  if [ "$currentVersion" != "$parsedRemoteVersion" ]; then
    echo "$repository version $parsedRemoteVersion is newer then $currentVersion"
    exit 1
  else
    echo "$repository is up to date"
    exit 0
  fi
}

if [ $# -lt 2 ]; then
  echo "check latest github release against a given version"
  echo
  echo "Syntax: docker run jansepke/github-release-checker user/repository version"
  echo "example:"
  echo "  hashicorp/terraform v0.12.0"
  exit 1
fi

main "$@"
